server:
  port: 6868

eureka:
  client:
    register-with-eureka: false #是否将自己注册到eureka中，这里是服务器不用注册
    fetch-registry: false #是否从eureka中获取信息，false表示自己为注册中心
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/